default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: taskv_development

test:
  <<: *default
  database: taskv_test

production:
  password: <%= ENV['TASKV_DATABASE_PASSWORD'] %>
