# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50db7e03660cb596ea9fa33a6e3f929bf3fbdee4a5f8c68b411f76be895f94fe58052a24989d2e15dd4da59bd27a1afe01cba8aeb90872b4d75c3e5b5360d61c

test:
  secret_key_base: b5247f7ad31f0c0f715e597201f603f1f13aac78fa9e4cfa0a4889b5c19587c6335704ebc7ed7271375f12b1772f5bb308bd41246ef4eb6caddfaf154dbcc4d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
